js:
  compress    : false
  verbose     : true
  output      : 'lib/turf/turfkit.js'
  input       :
    - src/google/maps/extended_api.js
    - src/extensions.coffee
    - src/turf/core/infowindow.coffee
    - src/turf/core/map.coffee
    - src/turf/core/marker.coffee
    - src/turf/core/point.coffee
    - src/turf/client/filter.coffee
    - src/turf/client/results.coffee
    - src/turf/client/application.coffee
